analyzer:
  exclude:
    - "packages/*/.dart_tool/**"
    - "packages/*/example/.dart_tool/**"
    - "packages/*/example/build/**"
    - "packages/*/build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
